spring.application.name=JWT-SpringBoot-Authenctication
spring.datasource.url=jdbc:mysql://localhost:3306/jwtuser
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
jwt.secretKey=slkjdfls4654seref423sdfsd5f6grvyuiy5mjn2uuuu6